-- AlterEnum
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_STARTED';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_FIELD_VIEWED';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_FIELD_COMPLETED';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_FIELD_SKIPPED';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_SECTION_COMPLETED';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_COMPLETION_25';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_COMPLETION_50';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_COMPLETION_75';
ALTER TYPE "ResearchEventType" ADD VALUE 'PROFILE_COMPLETION_90';
ALTER TYPE "ResearchEventType" ADD VALUE 'PHONE_VERIFICATION_REQUESTED';
ALTER TYPE "ResearchEventType" ADD VALUE 'PHONE_VERIFICATION_COMPLETED';

-- AlterTable
ALTER TABLE "UserPreferences" ADD COLUMN     "familySize" TEXT,
ADD COLUMN     "familyIncomeRange" TEXT;
