-- AlterEnum
ALTER TYPE "ResearchEventType" ADD VALUE 'LOCKED_FEATURE_CLICKED';
ALTER TYPE "ResearchEventType" ADD VALUE 'SIGNUP_COMPLETED';
ALTER TYPE "ResearchEventType" ADD VALUE 'LOGIN_COMPLETED';
